name: Conventional PR Title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Check Title
        id: check_title
        uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
