name: Python Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Extract Package Name
        id: extract_package_name
        run: |
          PACKAGE_NAME=$(poetry version | cut -d ' ' -f 1)
          echo "package_name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: ${{ steps.extract_package_name.outputs.package_name }}
