name: Python Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.REN_APP_ID }}
          private_key: ${{ secrets.REN_APP_KEY }}

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          token: ${{ steps.generate-token.outputs.token }}
