# 📘 Full documentation:
# https://github.com/renalreg/.github/blob/main/README.md#python-test-workflow


name: Python Test

on:
  pull_request:
    branches:
      - "master"

  workflow_dispatch:

jobs:
  call-workflow:
    name: Running python tests
    uses: renalreg/.github/.github/workflows/python_test.yml@main
    secrets: inherit
    with:  
      python_versions: '["3.12"]'

      os: '["windows-latest"]'
      package_manager_command: "pip install poetry"
      install_command: "poetry install"
      test_command: "poetry run tox"
      org_deps: true
