name: Python File Check

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  file_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Files Included Check
        id: file_check
        uses: andstor/file-existence-action@v2
        with:
          files: "README.md, CHANGELOG.md, pyproject.toml, tox.ini, LICENSE"

      - name: Fail If Files Missing
        if: steps.file_check.outputs.files_exists == 'false'
        run: |
          echo "You are missing one of the follwoing files"
          echo "README.md, CHANGELOG.md, pyproject.toml, tox.ini"
          echo "Please add the missing files and try again."
          exit 1

      - name: README Not Empty Check
        run: |
          if [ -s "README.md" ]; then
            echo "README is not empty 👍"
          else
            echo "README is empty 👎"
            exit 1
          fi
